2019-09-13 14:09:24,687 - INFO - Бот запускается
2019-09-13 14:09:29,746 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x111443890>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot742686631:AAGu4c56XHQrA4_OxlwkxcM6Ec-PrCybAF0/getMe
2019-09-13 14:09:34,755 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<telegram.vendor.ptb_urllib3.urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x111443a10>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot742686631:AAGu4c56XHQrA4_OxlwkxcM6Ec-PrCybAF0/getMe
